Categories: handle symlinks in the build system
elementary/icons pull request #1279
Opened 2024-05-14 22:40 UTC by danirabbit

2024-05-16 13:39 UTC, tintou requested changes
```
Tried to install symlink to missing file /usr/local/share/icons/elementary/apps/16/applications-internet.svg
```

2024-05-16 16:01 UTC, danirabbit commented
@tintou sorry about that :sweat_smile: fixed

2024-05-17 14:34 UTC, tintou commented on categories/meson.build
> +        if (fs.exists(link[1] + '.svg'))
```suggestion
        if (fs.exists(link[1] + '.svg'))
```
This looks wrong to me, is anything installed?

2024-05-17 16:40 UTC, danirabbit commented
@tintou Okay sorry for so many pings :sweat_smile: I think it's actually fixed now!

2024-08-13 19:02 UTC, merged